config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'events#index'
  resources :events
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	validates :stripe_customer_id, uniqueness: true

	belongs_to :user
	belongs_to :event

	after_create :attendance_confirmation_send
  def attendance_confirmation_send
    AttendanceMailer.attendance_confirmation_email(self).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord
	include ActiveModel::Validations

	belongs_to :user
	validates :start_date, :duration, :location, presence: true
  validates :title, length: { in: 20..1000 }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 1000  }
	validate :start_date_cannot_be_in_the_past, :duration_must_be_greater_than_0_and_multiple_by_5

	def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "La date ne peut pas être dans le passé.")
    end
  end

  def duration_must_be_greater_than_0_and_multiple_by_5
    if duration.present? && duration <= 0
      errors.add(:duration, "La durée doit être positive")
    end
    if duration.present? && (duration % 5) != 0
      errors.add(:duration, "La durée doit être un multiple de 5")
    end
  end

  has_many :attendances
  has_many :users, through: :attendances

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :attendances
	has_many :users, through: :attendances

	after_create :welcome_send
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  	#permet d'afficher une alerte à l'utilisateur
    puts flash[:alert]

    puts "-" * 60
    puts "Voici le nom du dernier auteur :"
    @events_list = Event.all
    puts @events_list[-1].user.last_name
    puts "-" * 60
  end

  def new
  end

  def show  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<br/>
<br/>
<div class="jumbotron jumbotron-fluid" style="background-color:#FEF4F7">
  <div class="container">
    <h1 class="display-5" style="color:#7146B2">💫 Bienvenue sur la page d'accueil de Majestical Eventbrite 💫</h1>
    <p class="text-center">Tu trouveras ci dessous la liste des derniers évènements en vogue 👀</p>
  </div>
</div>

  <!-- Ajout de la fonctionnalité qui permet d'ajouter une alerte au user-->
  <% if flash[:alert] != nil %>
    <div class='alert alert-success mt-4'>
      <%= flash[:alert] %>
    </div>
    <% end %>


<% @events_list.each.with_index(1) do |event| %>
 	<div class="card-deck" style="margin-left: 15px; margin-right: 15px">
 	<div class="card" style="width: 18rem;">
  	<div class="card-body">
    	<h5 class="card-title">Event n° <%= event.id %> - "<%= event.title %>"</h5>
    	<h6 class="card-subtitle mb-2 text-muted">Lieu : <%= event.location %> - Cet évènement est organisé : <%= event.user.first_name %></h6>
    	<p class="card-text"><%= event.description %></p>
   	 <a href="<%= event_path(event.id) %>" class="card-link"> Cliquez pour plus d'infos: </a>
 		</div>
 		</div>
	</div>
<br/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Majestical EventBrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:#7146B2">
      <a class="navbar-brand" href="<%= root_path %>">Majestical Eventbrite</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= events_path %>">Accueil <span class="sr-only">(current)</span></a>
          </li>

          <li class="nav-item">
           <a class="nav-link" href="#">Nouveau Event</a>
          </li>

          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mon profil</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="<%= edit_user_registration_path %>">Mon profil</a>
              <div class="dropdown-divider"></div>
              <div class="dropdown-item"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></div>
              
              </div>
            </li>
          <% else %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">S'inscrire / Se connecter</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="<%= new_user_registration_path %>">S'inscrire</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="<%= new_user_session_path %>">Se connecter</a>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>